# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Dev\Spikes\PythonExamples\PythonExamples\AsyncButton\source_files\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import time

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 191)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.button_do_something = QtWidgets.QPushButton(self.centralwidget)
        self.button_do_something.setGeometry(QtCore.QRect(20, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_do_something.setFont(font)
        self.button_do_something.setObjectName("button_do_something")
        self.txt_module_one = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_module_one.setGeometry(QtCore.QRect(200, 20, 113, 31))
        self.txt_module_one.setObjectName("txt_module_one")
        self.txt_module_two = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_module_two.setGeometry(QtCore.QRect(200, 60, 113, 31))
        self.txt_module_two.setObjectName("txt_module_two")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 488, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Basic PYQT5 In OUT Example"))
        self.label.setText(_translate("MainWindow", "Module One Value"))
        self.label_2.setText(_translate("MainWindow", "Module Two Value"))
        self.button_do_something.setText(_translate("MainWindow", "Example Action"))


    def start_gui(self):
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        app.exec_()

        # running an application loop
        # sys.exit(app.exec_())

    def dispose(self):
        # MainWindow.hide()
        print("Close window if closed form console")
